#!/bin/sh
echo "program name is: " $0
echo "first args is: " $1
echo "second arg is: " $2
echo "third arg is: " $3
echo "print all args: " $*
echo "print no.of args: " $#
echo "printing all arguments using \$@ " $@

